
import { Category } from './types';

export type SeedRecipe = {
  recipe_id: string;
  title: string;
  category: Category;
  short_description: string;
  servings: number;
  total_time_minutes: number;
  calories_estimate_kcal: number;
  calories_confidence: "estimate";
  equipment_needed: string[];
  seed_ingredients: string[];
  hero_ingredients: string[];
  source: "seed";
  rating: number;
  review_count: number;
};

export const SEED_RECIPES: SeedRecipe[] = [
  // --- 麵類 (10) ---
  { recipe_id: 'n-1', title: '台式紅燒牛肉麵', category: Category.NOODLES, short_description: '經典台式風味，牛腩軟嫩入味。', servings: 2, total_time_minutes: 120, calories_estimate_kcal: 750, calories_confidence: 'estimate', equipment_needed: ['壓力鍋', '湯鍋'], seed_ingredients: ['牛腩', '白蘿蔔', '手工麵條', '滷包', '豆瓣醬', '薑', '蔥'], hero_ingredients: ['牛腩', '手工麵'], source: 'seed', rating: 4.9, review_count: 1250 },
  { recipe_id: 'n-2', title: '川味擔擔麵', category: Category.NOODLES, short_description: '香辣濃郁的花生醬汁與Q彈麵條。', servings: 1, total_time_minutes: 20, calories_estimate_kcal: 550, calories_confidence: 'estimate', equipment_needed: ['炒鍋'], seed_ingredients: ['拉麵', '豬絞肉', '花生粉', '辣油', '花椒粉', '碎米芽菜'], hero_ingredients: ['豬絞肉', '花生醬'], source: 'seed', rating: 4.7, review_count: 850 },
  { recipe_id: 'n-3', title: '老北京炸醬麵', category: Category.NOODLES, short_description: '鹹香乾醬，搭配爽口小菜。', servings: 2, total_time_minutes: 30, calories_estimate_kcal: 600, calories_confidence: 'estimate', equipment_needed: ['炒鍋'], seed_ingredients: ['粗麵', '豬五花肉丁', '甜麵醬', '黃豆醬', '小黃瓜絲', '豆芽'], hero_ingredients: ['甜麵醬', '豬五花'], source: 'seed', rating: 4.6, review_count: 420 },
  { recipe_id: 'n-4', title: '台式肉燥乾拌麵', category: Category.NOODLES, short_description: '家鄉的味道，油蔥酥香氣逼人。', servings: 2, total_time_minutes: 15, calories_estimate_kcal: 480, calories_confidence: 'estimate', equipment_needed: ['湯鍋'], seed_ingredients: ['意麵', '肉燥滷汁', '油蔥酥', '青江菜', '滷蛋'], hero_ingredients: ['油蔥酥', '意麵'], source: 'seed', rating: 4.8, review_count: 980 },
  { recipe_id: 'n-5', title: '日式和風涼麵', category: Category.NOODLES, short_description: '清爽低負擔，夏日必備首選。', servings: 1, total_time_minutes: 10, calories_estimate_kcal: 350, calories_confidence: 'estimate', equipment_needed: ['湯鍋'], seed_ingredients: ['細拉麵', '鰹魚醬油', '雞絲', '小黃瓜', '蛋絲', '芥末'], hero_ingredients: ['雞絲', '鰹魚醬油'], source: 'seed', rating: 4.5, review_count: 310 },
  { recipe_id: 'n-6', title: '韓式炒馬麵', category: Category.NOODLES, short_description: '海鮮鮮味與辣椒粉的辛香。', servings: 2, total_time_minutes: 25, calories_estimate_kcal: 680, calories_confidence: 'estimate', equipment_needed: ['炒鍋'], seed_ingredients: ['拉麵', '蛤蜊', '蝦仁', '洋蔥', '韓式辣椒粉', '豬肉片'], hero_ingredients: ['蛤蜊', '海蝦'], source: 'seed', rating: 4.6, review_count: 560 },
  { recipe_id: 'n-7', title: '上海蔥油拌麵', category: Category.NOODLES, short_description: '熬製蔥油，簡約卻不平凡。', servings: 1, total_time_minutes: 15, calories_estimate_kcal: 420, calories_confidence: 'estimate', equipment_needed: ['炒鍋'], seed_ingredients: ['細麵', '青蔥', '生抽', '老抽', '白糖'], hero_ingredients: ['青蔥', '老抽'], source: 'seed', rating: 4.8, review_count: 1100 },
  { recipe_id: 'n-8', title: '山西削麵燉排骨', category: Category.NOODLES, short_description: '嚼勁十足的削麵搭配濃郁肉湯。', servings: 2, total_time_minutes: 60, calories_estimate_kcal: 720, calories_confidence: 'estimate', equipment_needed: ['燉鍋'], seed_ingredients: ['刀削麵', '豬排骨', '醬油', '八角', '桂皮', '土豆塊'], hero_ingredients: ['排骨', '刀削麵'], source: 'seed', rating: 4.7, review_count: 240 },
  { recipe_id: 'n-9', title: '鍋燒意麵', category: Category.NOODLES, short_description: '台南在地風味，炸意麵口感獨特。', servings: 1, total_time_minutes: 15, calories_estimate_kcal: 580, calories_confidence: 'estimate', equipment_needed: ['鍋燒鍋'], seed_ingredients: ['炸意麵', '雞蛋', '貢丸', '小白菜', '蝦子', '柴魚高湯'], hero_ingredients: ['炸意麵', '柴魚高湯'], source: 'seed', rating: 4.4, review_count: 890 },
  { recipe_id: 'n-10', title: '酸辣手撕拌麵', category: Category.NOODLES, short_description: '醋酸爽口，手撕口感更有趣。', servings: 1, total_time_minutes: 15, calories_estimate_kcal: 460, calories_confidence: 'estimate', equipment_needed: ['湯鍋'], seed_ingredients: ['寬麵', '陳醋', '辣椒油', '大蒜泥', '花生碎', '香菜'], hero_ingredients: ['陳醋', '寬麵'], source: 'seed', rating: 4.3, review_count: 150 },

  // --- 飯類 (10) ---
  { recipe_id: 'r-1', title: '招牌滷肉飯', category: Category.RICE, short_description: '肥而不膩，滿滿膠質的幸福感。', servings: 4, total_time_minutes: 90, calories_estimate_kcal: 550, calories_confidence: 'estimate', equipment_needed: ['燉鍋'], seed_ingredients: ['白飯', '豬皮帶肥五花肉', '油蔥酥', '冰糖', '五香粉'], hero_ingredients: ['五花肉', '油蔥酥'], source: 'seed', rating: 4.9, review_count: 3200 },
  { recipe_id: 'r-2', title: '生炒牛肉炒飯', category: Category.RICE, short_description: '鑊氣十足，粒粒分明。', servings: 1, total_time_minutes: 15, calories_estimate_kcal: 620, calories_confidence: 'estimate', equipment_needed: ['炒鍋'], seed_ingredients: ['冷飯', '牛肉絲', '雞蛋', '青蔥', '醬油'], hero_ingredients: ['牛肉絲', '冷飯'], source: 'seed', rating: 4.8, review_count: 670 },
  { recipe_id: 'r-3', title: '海南雞飯', category: Category.RICE, short_description: '雞油悶飯，搭配嫩滑雞腿。', servings: 2, total_time_minutes: 45, calories_estimate_kcal: 680, calories_confidence: 'estimate', equipment_needed: ['電鍋'], seed_ingredients: ['泰國香米', '大雞腿', '班蘭葉', '香茅', '薑黃'], hero_ingredients: ['大雞腿', '香米'], source: 'seed', rating: 4.7, review_count: 1450 },
  { recipe_id: 'r-4', title: '日式豬排蛋包飯', category: Category.RICE, short_description: '小朋友最愛，半熟蛋皮滑嫩無比。', servings: 1, total_time_minutes: 30, calories_estimate_kcal: 850, calories_confidence: 'estimate', equipment_needed: ['炸鍋', '平底鍋'], seed_ingredients: ['白飯', '里肌豬排', '雞蛋', '番茄醬', '鮮奶'], hero_ingredients: ['豬排', '雞蛋'], source: 'seed', rating: 4.6, review_count: 820 },
  { recipe_id: 'r-5', title: '廣式臘味煲仔飯', category: Category.RICE, short_description: '香脆鍋巴，臘味鹹甜入味。', servings: 2, total_time_minutes: 40, calories_estimate_kcal: 720, calories_confidence: 'estimate', equipment_needed: ['砂鍋'], seed_ingredients: ['絲苗米', '臘腸', '肝腸', '廣東菜心', '煲仔飯醬油'], hero_ingredients: ['臘腸', '砂鍋'], source: 'seed', rating: 4.7, review_count: 340 },
  { recipe_id: 'r-6', title: '奶油蘑菇燉飯', category: Category.RICE, short_description: '法式風情，濃郁奶香。', servings: 2, total_time_minutes: 35, calories_estimate_kcal: 580, calories_confidence: 'estimate', equipment_needed: ['平底鍋'], seed_ingredients: ['義大利米', '蘑菇', '鮮奶油', '帕瑪森起司', '洋蔥'], hero_ingredients: ['蘑菇', '起司'], source: 'seed', rating: 4.5, review_count: 290 },
  { recipe_id: 'r-7', title: '櫻花蝦高麗菜炒飯', category: Category.RICE, short_description: '鮮香爽脆，層次豐富。', servings: 1, total_time_minutes: 15, calories_estimate_kcal: 510, calories_confidence: 'estimate', equipment_needed: ['炒鍋'], seed_ingredients: ['冷飯', '櫻花蝦', '高麗菜絲', '蛋', '蔥花'], hero_ingredients: ['櫻花蝦', '高麗菜'], source: 'seed', rating: 4.4, review_count: 180 },
  { recipe_id: 'r-8', title: '上海菜飯', category: Category.RICE, short_description: '鹹肉提鮮，青菜清甜。', servings: 2, total_time_minutes: 30, calories_estimate_kcal: 490, calories_confidence: 'estimate', equipment_needed: ['電鍋'], seed_ingredients: ['白米', '青江菜', '家鄉肉(鹹肉)', '紹興酒'], hero_ingredients: ['青江菜', '鹹肉'], source: 'seed', rating: 4.3, review_count: 120 },
  { recipe_id: 'r-9', title: '韓式石鍋拌飯', category: Category.RICE, short_description: '五彩繽紛，香辣開胃。', servings: 1, total_time_minutes: 25, calories_estimate_kcal: 640, calories_confidence: 'estimate', equipment_needed: ['石鍋'], seed_ingredients: ['白飯', '黃豆芽', '蕨菜', '牛肉末', '韓式辣醬', '荷包蛋'], hero_ingredients: ['韓式辣醬', '牛肉'], source: 'seed', rating: 4.7, review_count: 950 },
  { recipe_id: 'r-10', title: '紅豆油飯', category: Category.RICE, short_description: '節日氛圍，軟糯香甜。', servings: 4, total_time_minutes: 60, calories_estimate_kcal: 450, calories_confidence: 'estimate', equipment_needed: ['蒸籠', '電鍋'], seed_ingredients: ['長糯米', '紅豆', '芝麻粉', '砂糖'], hero_ingredients: ['長糯米', '紅豆'], source: 'seed', rating: 4.2, review_count: 90 },

  // --- 湯品 (10) ---
  { recipe_id: 's-1', title: '慢火燉雞湯', category: Category.SOUP, short_description: '純粹雞肉精華，鮮甜無比。', servings: 4, total_time_minutes: 120, calories_estimate_kcal: 320, calories_confidence: 'estimate', equipment_needed: ['燉鍋'], seed_ingredients: ['全雞', '老薑', '紹興酒', '乾香菇'], hero_ingredients: ['全雞', '乾香菇'], source: 'seed', rating: 5.0, review_count: 1100 },
  { recipe_id: 's-2', title: '番茄牛腩湯', category: Category.SOUP, short_description: '酸甜平衡，豐富纖維。', servings: 3, total_time_minutes: 90, calories_estimate_kcal: 420, calories_confidence: 'estimate', equipment_needed: ['燉鍋'], seed_ingredients: ['牛腩', '成熟番茄', '洋蔥', '紅蘿蔔', '黑胡椒'], hero_ingredients: ['牛腩', '番茄'], source: 'seed', rating: 4.8, review_count: 620 },
  { recipe_id: 's-3', title: '日式味噌蜆湯', category: Category.SOUP, short_description: '護肝聖品，早餐首選。', servings: 2, total_time_minutes: 15, calories_estimate_kcal: 80, calories_confidence: 'estimate', equipment_needed: ['湯鍋'], seed_ingredients: ['黃金蜆', '赤味噌', '嫩豆腐', '海帶芽', '蔥花'], hero_ingredients: ['黃金蜆', '味噌'], source: 'seed', rating: 4.7, review_count: 310 },
  { recipe_id: 's-4', title: '正宗四川酸辣湯', category: Category.SOUP, short_description: '層次感分明，酸、辣、香齊備。', servings: 2, total_time_minutes: 25, calories_estimate_kcal: 220, calories_confidence: 'estimate', equipment_needed: ['湯鍋'], seed_ingredients: ['木耳絲', '嫩豆腐', '豬血絲', '胡椒粉', '烏醋', '蛋液'], hero_ingredients: ['胡椒粉', '烏醋'], source: 'seed', rating: 4.6, review_count: 450 },
  { recipe_id: 's-5', title: '奶油玉米濃湯', category: Category.SOUP, short_description: '美式經典，滑順濃郁。', servings: 3, total_time_minutes: 30, calories_estimate_kcal: 380, calories_confidence: 'estimate', equipment_needed: ['湯鍋'], seed_ingredients: ['玉米粒罐頭', '洋蔥', '培根', '鮮奶', '麵粉', '奶油'], hero_ingredients: ['玉米', '培根'], source: 'seed', rating: 4.4, review_count: 520 },
  { recipe_id: 's-6', title: '剝皮辣椒雞湯', category: Category.SOUP, short_description: '花蓮名產，微辣帶甜。', servings: 4, total_time_minutes: 60, calories_estimate_kcal: 340, calories_confidence: 'estimate', equipment_needed: ['燉鍋'], seed_ingredients: ['土雞塊', '剝皮辣椒罐頭', '蛤蜊', '薑片'], hero_ingredients: ['剝皮辣椒', '土雞'], source: 'seed', rating: 4.9, review_count: 880 },
  { recipe_id: 's-7', title: '南瓜濃湯', category: Category.SOUP, short_description: '天然甜味，飽足感十足。', servings: 2, total_time_minutes: 30, calories_estimate_kcal: 280, calories_confidence: 'estimate', equipment_needed: ['果汁機', '湯鍋'], seed_ingredients: ['東昇南瓜', '洋蔥', '鮮奶油', '雞高湯'], hero_ingredients: ['南瓜', '洋蔥'], source: 'seed', rating: 4.5, review_count: 140 },
  { recipe_id: 's-8', title: '港式皮蛋瘦肉粥湯', category: Category.SOUP, short_description: '老火慢燉，綿密滋潤。', servings: 2, total_time_minutes: 60, calories_estimate_kcal: 310, calories_confidence: 'estimate', equipment_needed: ['電鍋'], seed_ingredients: ['白米', '皮蛋', '豬里肌', '油條'], hero_ingredients: ['皮蛋', '瘦肉'], source: 'seed', rating: 4.3, review_count: 90 },
  { recipe_id: 's-9', title: '義大利蔬菜大雜燴湯', category: Category.SOUP, short_description: '多種蔬菜，營養滿分。', servings: 4, total_time_minutes: 40, calories_estimate_kcal: 180, calories_confidence: 'estimate', equipment_needed: ['燉鍋'], seed_ingredients: ['西洋芹', '紅蘿蔔', '番茄', '西葫蘆', '通心粉'], hero_ingredients: ['番茄', '西洋芹'], source: 'seed', rating: 4.2, review_count: 70 },
  { recipe_id: 's-10', title: '藥膳排骨湯', category: Category.SOUP, short_description: '夜市飄香，滋補養身。', servings: 2, total_time_minutes: 90, calories_estimate_kcal: 450, calories_confidence: 'estimate', equipment_needed: ['燉鍋'], seed_ingredients: ['豬支骨', '藥膳包', '當歸', '米酒'], hero_ingredients: ['藥膳包', '排骨'], source: 'seed', rating: 4.8, review_count: 550 },

  // --- 火鍋 (10) ---
  { recipe_id: 'h-1', title: '四川麻辣火鍋', category: Category.HOTPOT, short_description: '辛辣刺激，香麻過癮。', servings: 4, total_time_minutes: 60, calories_estimate_kcal: 1200, calories_confidence: 'estimate', equipment_needed: ['電磁爐', '火鍋盆'], seed_ingredients: ['牛油火鍋底料', '鴨血', '豆腐', '牛肚', '老肉片'], hero_ingredients: ['麻辣底料', '鴨血'], source: 'seed', rating: 4.9, review_count: 1800 },
  { recipe_id: 'h-2', title: '日式昆布柴魚鍋', category: Category.HOTPOT, short_description: '清爽無負擔，品嚐食材原味。', servings: 2, total_time_minutes: 20, calories_estimate_kcal: 400, calories_confidence: 'estimate', equipment_needed: ['火鍋'], seed_ingredients: ['昆布', '柴魚片', '白蘿蔔', '嫩豆腐'], hero_ingredients: ['昆布', '柴魚'], source: 'seed', rating: 4.7, review_count: 640 },
  { recipe_id: 'h-3', title: '香濃起司牛奶鍋', category: Category.HOTPOT, short_description: '少女心爆棚，溫潤滑順。', servings: 2, total_time_minutes: 30, calories_estimate_kcal: 950, calories_confidence: 'estimate', equipment_needed: ['火鍋'], seed_ingredients: ['全脂牛奶', '高湯', '起司片', '雞肉塊'], hero_ingredients: ['牛奶', '起司'], source: 'seed', rating: 4.6, review_count: 420 },
  { recipe_id: 'h-4', title: '正宗羊肉爐', category: Category.HOTPOT, short_description: '冬令進補，驅寒保暖。', servings: 4, total_time_minutes: 90, calories_estimate_kcal: 850, calories_confidence: 'estimate', equipment_needed: ['瓦斯爐', '燉鍋'], seed_ingredients: ['帶皮羊肉', '中藥材包', '薑母', '凍豆腐'], hero_ingredients: ['羊肉', '中藥'], source: 'seed', rating: 4.8, review_count: 1300 },
  { recipe_id: 'h-5', title: '老牌薑母鴨', category: Category.HOTPOT, short_description: '辛辣薑味，濃郁酒香。', servings: 4, total_time_minutes: 80, calories_estimate_kcal: 920, calories_confidence: 'estimate', equipment_needed: ['陶鍋'], seed_ingredients: ['番鴨', '老薑', '麻油', '紅標米酒'], hero_ingredients: ['鴨肉', '老薑'], source: 'seed', rating: 4.7, review_count: 910 },
  { recipe_id: 'h-6', title: '砂鍋魚頭', category: Category.HOTPOT, short_description: '嘉義特產，鮮味十足。', servings: 4, total_time_minutes: 60, calories_estimate_kcal: 780, calories_confidence: 'estimate', equipment_needed: ['砂鍋'], seed_ingredients: ['大頭鰱魚頭', '沙茶醬', '大白菜', '蛋酥'], hero_ingredients: ['魚頭', '沙茶醬'], source: 'seed', rating: 4.8, review_count: 750 },
  { recipe_id: 'h-7', title: '東北酸菜白肉鍋', category: Category.HOTPOT, short_description: '酸爽解膩，五花肉片絕配。', servings: 3, total_time_minutes: 45, calories_estimate_kcal: 650, calories_confidence: 'estimate', equipment_needed: ['銅鍋'], seed_ingredients: ['酸白菜', '豬五花薄片', '凍豆腐', '蝦米'], hero_ingredients: ['酸白菜', '五花肉'], source: 'seed', rating: 4.5, review_count: 280 },
  { recipe_id: 'h-8', title: '韓式部隊鍋', category: Category.HOTPOT, short_description: '美式融合，罪惡感美食。', servings: 2, total_time_minutes: 25, calories_estimate_kcal: 1100, calories_confidence: 'estimate', equipment_needed: ['火鍋'], seed_ingredients: ['韓式拉麵', '午餐肉', '熱狗', '泡菜', '起司'], hero_ingredients: ['午餐肉', '拉麵'], source: 'seed', rating: 4.4, review_count: 670 },
  { recipe_id: 'h-9', title: '壽喜燒 (Sukiyaki)', category: Category.HOTPOT, short_description: '甜鹹醬汁，雞蛋液點睛之筆。', servings: 2, total_time_minutes: 30, calories_estimate_kcal: 820, calories_confidence: 'estimate', equipment_needed: ['淺平鍋'], seed_ingredients: ['頂級牛肉片', '大蔥', '蒟蒻絲', '壽喜燒醬汁'], hero_ingredients: ['牛肉片', '大蔥'], source: 'seed', rating: 4.8, review_count: 1150 },
  { recipe_id: 'h-10', title: '潮汕牛肉火鍋', category: Category.HOTPOT, short_description: '清湯掛麵，現切牛肉。', servings: 4, total_time_minutes: 40, calories_estimate_kcal: 550, calories_confidence: 'estimate', equipment_needed: ['火鍋'], seed_ingredients: ['牛骨湯', '新鮮牛肉片', '沙茶醬', '玉米'], hero_ingredients: ['牛骨湯', '現切牛'], source: 'seed', rating: 4.3, review_count: 190 },

  // --- 甜點 (10) ---
  { recipe_id: 'd-1', title: '古法手工豆花', category: Category.DESSERT, short_description: '綿密口感，自製甜水。', servings: 4, total_time_minutes: 60, calories_estimate_kcal: 220, calories_confidence: 'estimate', equipment_needed: ['煮鍋'], seed_ingredients: ['黃豆', '熟石膏粉', '地瓜粉', '薑糖水'], hero_ingredients: ['黃豆', '薑糖水'], source: 'seed', rating: 4.8, review_count: 1400 },
  { recipe_id: 'd-2', title: '楊枝甘露', category: Category.DESSERT, short_description: '港式經典，層次分明。', servings: 2, total_time_minutes: 30, calories_estimate_kcal: 380, calories_confidence: 'estimate', equipment_needed: ['果汁機'], seed_ingredients: ['愛文芒果', '葡萄柚', '西米露', '椰奶'], hero_ingredients: ['芒果', '椰奶'], source: 'seed', rating: 4.9, review_count: 920 },
  { recipe_id: 'd-3', title: '車輪餅 (紅豆口味)', category: Category.DESSERT, short_description: '爆漿內餡，外皮酥脆。', servings: 6, total_time_minutes: 45, calories_estimate_kcal: 250, calories_confidence: 'estimate', equipment_needed: ['紅豆餅模具'], seed_ingredients: ['麵粉', '雞蛋', '蜜紅豆', '鮮奶'], hero_ingredients: ['蜜紅豆', '雞蛋'], source: 'seed', rating: 4.7, review_count: 840 },
  { recipe_id: 'd-4', title: '黑糖珍珠鮮奶酪', category: Category.DESSERT, short_description: 'Q彈珍珠與濃郁奶香。', servings: 4, total_time_minutes: 40, calories_estimate_kcal: 320, calories_confidence: 'estimate', equipment_needed: ['煮鍋', '冰箱'], seed_ingredients: ['鮮奶', '吉利丁', '黑糖', '木薯粉珍珠'], hero_ingredients: ['黑糖珍珠', '鮮奶'], source: 'seed', rating: 4.6, review_count: 510 },
  { recipe_id: 'd-5', title: '草莓提拉米蘇', category: Category.DESSERT, short_description: '粉紅浪漫，酸甜滋味。', servings: 4, total_time_minutes: 45, calories_estimate_kcal: 450, calories_confidence: 'estimate', equipment_needed: ['冰箱', '打蛋器'], seed_ingredients: ['手指餅乾', '馬斯卡彭起司', '草莓', '草莓甜酒'], hero_ingredients: ['草莓', '馬斯卡彭'], source: 'seed', rating: 4.8, review_count: 230 },
  { recipe_id: 'd-6', title: '桂花糖藕', category: Category.DESSERT, short_description: '江浙名點，軟糯清香。', servings: 4, total_time_minutes: 120, calories_estimate_kcal: 280, calories_confidence: 'estimate', equipment_needed: ['燉鍋'], seed_ingredients: ['蓮藕', '糯米', '冰糖', '乾桂花'], hero_ingredients: ['蓮藕', '桂花'], source: 'seed', rating: 4.4, review_count: 110 },
  { recipe_id: 'd-7', title: '鳳梨酥', category: Category.DESSERT, short_description: '台灣伴手禮，純土鳳梨內餡。', servings: 12, total_time_minutes: 90, calories_estimate_kcal: 180, calories_confidence: 'estimate', equipment_needed: ['烤箱'], seed_ingredients: ['土鳳梨膏', '麵粉', '發酵奶油', '奶粉'], hero_ingredients: ['鳳梨餡', '奶油'], source: 'seed', rating: 4.9, review_count: 1600 },
  { recipe_id: 'd-8', title: '手搓黑芝麻湯圓', category: Category.DESSERT, short_description: '冬至暖心，流沙質感。', servings: 4, total_time_minutes: 60, calories_estimate_kcal: 420, calories_confidence: 'estimate', equipment_needed: ['煮鍋'], seed_ingredients: ['糯米粉', '黑芝麻粉', '豬油', '白砂糖'], hero_ingredients: ['黑芝麻', '糯米粉'], source: 'seed', rating: 4.7, review_count: 480 },
  { recipe_id: 'd-9', title: '日式抹茶厥餅', category: Category.DESSERT, short_description: '入口即化，茶味甘醇。', servings: 2, total_time_minutes: 20, calories_estimate_kcal: 210, calories_confidence: 'estimate', equipment_needed: ['煮鍋'], seed_ingredients: ['厥餅粉', '抹茶粉', '黑糖蜜', '黃豆粉'], hero_ingredients: ['抹茶', '黑糖蜜'], source: 'seed', rating: 4.5, review_count: 310 },
  { recipe_id: 'd-10', title: '泰式芒果糯米飯', category: Category.DESSERT, short_description: '椰香撲鼻，南國風情。', servings: 2, total_time_minutes: 40, calories_estimate_kcal: 490, calories_confidence: 'estimate', equipment_needed: ['電鍋'], seed_ingredients: ['圓糯米', '泰國芒果', '濃縮椰漿', '斑蘭葉'], hero_ingredients: ['芒果', '椰漿'], source: 'seed', rating: 4.6, review_count: 760 },
];
